### PR TITLE
its a really bad idea to execute scripts you blindly download from the internet

### PR DESCRIPTION
**Pull request by williame**

### CODE REVIEW

**Comment by gpakosz** [comment]
@afshinm why the hell did you merge it in the first place? Come on, as if the diff wasn't obvious...

**Comment by afshinm** [comment]
I think @williame didn't understant correctly the difference between **issue** and **pull request**. If anybody has a comment/problem with the repository, should notify the repository owner with a **issue** not a **pull request**.

**Comment by jimeh** [comment]
@afshinm It's generally a good idea to actually check the diff of a pull request before merging it :)

**Comment by afshinm** [comment]
Guys guys, again I say I know that's my fault and I'm really sorry and shame for that but please keep it in your mind that @williame should create a issue and not a pull request!!!

**Comment by benjamineskola** [comment]
@afshinm Don't pass the blame on to @williame, the problem is not that he chose to demonstrate the problem in this way but the fact that you didn't check it before merging, which just makes the original problem even worse.

**Comment by afshinm** [comment]
@bma I think you didn't read my comment completely: 

> again I say I know that's my fault and I'm really sorry

**Comment by benjamineskola** [comment]
@afshinm I did, then I read the part after that where you tried to blame someone else for it.

**Comment by jimeh** [comment]
@afshinm Issue or pull request doesn't matter. Pull requests should be treated with caution, not blind faith. Same goes for [issues](https://github.com/afshinm/valentine_script/issues/8) too ;)... lol

**Comment by williame** [comment]
@afshinm Its been a full day now and yet you persist in encouraging people to blindly execute from the internet in general and content you control and are responsible for in particular.

What, are you waiting to pull your own prank on the 14th or?  Contemptible.

**Pull request merged**
